parameters:
#    opwoco_forecast.example.class: opwoco\ForecastBundle\Example

services:
#    opwoco_forecast.example:
#        class: %opwoco_forecast.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
